spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/crimsonstore
    password: root
    driver-class-name: org.postgresql.Driver
    username: postgres
    dialect: org.hibernate.dialect.PostgreSQL10Dialect
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create
server:
  port: 8081